name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq lcov
      - name: build
        run: |
          make -B
      - name: tests
        run: |
          make tests
      - name: coverage
        run: |
          make coverage
        env:
          CC: gcc
          CXX: g++
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq lcov
      - name: build
        run: |
          make -B
      - name: tests
        run: |
          make tests
      - name: coverage
        run: |
          make coverage
        env:
          CC: clang
          CXX: clang++
